parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
root: true
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-namespace': 0
